---
name: owserver (1-wire)
version: 0.4.0
slug: owserver-enet
description: onewire server to read 1-Wire devices incl. enet direct access via TCP
url: https://github.com/romeocontrol/hassio-owserver-enet
startup: system
init: false
arch: 
  - amd64
  - aarch64
  - armhf
  - armv7
boot: auto  
uart: true
options:
  owhttpd: true
  temperature_scale: Celsius
schema:
  owhttpd: bool
  serial_device: serial_device
  serial_device_type: list(serial_or_i2c|usb|fake)
  tcp_device: tcp_device
  tcp_device_type: list(ha7net|enet)
  temperature_scale: list(Celsius|Fahrenheit|Kelvin|Rankine)
  ha7net_server: str?
  enet_server: str?
  debug: bool?
ingress: true
panel_icon: mdi:alpha-w-box
image: ghcr.io/lrybak/owserver/{arch}
